### ISSUE TITLE
No colorful outputs for `Dev` command.

### ISSUE THREAD

**Issue by Tnze** [tauri-apps/tauri-vscode#228]
Current:
![image](https://github.com/tauri-apps/tauri-vscode/assets/19628575/1f90a811-f702-448b-be7a-e80ec40e6835)

Wanted:
![image](https://github.com/tauri-apps/tauri-vscode/assets/19628575/bdd4f118-24f3-4eae-85dc-cceb907ffbc5)

**Comment by FabianLars** [comment]
Last time i checked the Output tab doesn't support colors and requires something like this extension https://marketplace.visualstudio.com/items?itemName=IBM.output-colorizer

We even had to start stripping the color information since it completely broke the output formatting https://github.com/tauri-apps/tauri-vscode/blob/dev/src/extension.ts#L346
